- hosts: localhost
  gather_facts: no
  tasks:
  - name: install packages
    become: true
    yum:
      state: present
      name:
       - httpd
  - name: Hello Message
    debug:
       msg: "Hello World!"
     
