- hosts: all
  gather_facts: no
  tasks:
  - name: install packages for apache
    become: true
    yum:
      state: present
      name:
       - httpd
  - name: Hello Message
    debug:
       msg: "Hello World!"
     
